# Generated by Django 5.1.6 on 2025-02-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_age_client_doc_id_client_doc_id_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='training_plan',
            field=models.CharField(choices=[('Musculacion', 'Musculacion'), ('Crossfit', 'Crossfit'), ('Full', 'Full')], default='Musculacion', max_length=50),
        ),
    ]
